### ISSUE TITLE
serial error in red

### ISSUE THREAD

**Issue by Rothammel** [xenpac/ESP32-CAM-Linux-Motion#4]
E (979732) task_wdt: Task watchdog got triggered. The following tasks did not reset the watchdog in time:
E (979732) task_wdt:  - IDLE (CPU 0)
E (979732) task_wdt: Tasks currently running:
E (979732) task_wdt: CPU 0: main
E (979732) task_wdt: CPU 1: IDLE
E (979732) task_wdt: Print CPU 0 (current core) backtrace

Backtrace:0x400EDBEF:0x3FFB0C700x40083E89:0x3FFB0C90 0x4008D615:0x3FFBA0A0 0x4000BE96:0x3FFBA0C0 0x4000177B:0x3FFBA0E0 0x400D92F8:0x3FFBA100 0x400D9397:0x412D6E65  |<-CORRUPTED

E (979732) task_wdt: Print CPU 1 backtrace

Backtrace:0x40085C4D:0x3FFB12700x40083E89:0x3FFB1290 0x4000BFED:0x3FFBB770 0x4008EFA5:0x3FFBB780 0x400EDE8F:0x3FFBB7A0 0x400EDE9B:0x3FFBB7C0 0x400D2702:0x3FFBB7E0 0x4008CFFC:0x3FFBB800

**Comment by xenpac** [comment]
disable the WDT in project config.
there is a bootloader watchdog and a task watchdog.
however they should be resetted properly by default.
