### ISSUE TITLE
Error when trying to make.

### ISSUE THREAD

**Issue by rbretmounet** [xenpac/ESP32-CAM-Linux-Motion#5]
I get this error when trying to build. 
D:/esp_projects/ESP32-CAM-Linux-Motion-main/main/tcpserver.c:27:10: fatal error: esp_wifi.h: No such file or directory
   27 | #include "esp_wifi.h"
      |          ^~~~~~~~~~~~

**Comment by xenpac** [comment]
this project is based on esp idf 4.3 or 4.4.
rebase your environment to this version.
