### ISSUE TITLE
Error Putty

### ISSUE THREAD

**Issue by fiduchi** [xenpac/ESP32-CAM-Linux-Motion#6]
I can’t connect via putty, the terminal freezes and nothing happens. Is it possible to upload this firmware via arduino somehow?

**Comment by xenpac** [comment]
i dont know arduinos way of flashing.
but make shure your cable is properly connected.
after reset the cam it should output something on to your terminal like waiting for download or so.
it should work with the procedure documented in docu.
esp idf version 4.3 or 4.4 is recommedned for this project.
