### ISSUE TITLE
Commandline parameter?

### ISSUE THREAD

**Issue by Haititei** [xenpac/ESP32-CAM-Linux-Motion#8]
In the original esp32cam webcam I can change the parameters directly in the browser in the format http://ip-adress/control?var=<variable name>&val=<value>. Is there a variable for the LED?

I found this variables in the web:
Description Variblenname Values
Resolution framesize 10 UXGA(1600×1200)
                                          9 SXGA(1280×1024)
                                          8 XGA(1024×768)
                                         7 SVGA(800×600)
                                         6 VGA(640×480)
                                         5 CIF(400×296)
                                         4 QVGA(320×240)
                                         3 HQVGA(240×176)
                                         0 QQVGA(160×120)
                                         4 Preset
Picture quality 10 good to
                                    63 poor
                                   10 Preset
Brightness brightness -2 to 2
                                     0 Preset
Contrast contrast -2 to 2
                                  0 Preset
Saturation saturation -2 to 2
                                        0 Preset
Special effects special_effect 0 No effect
                                               1 Negative image
                                              2 Black/white
                                              3 Red complexion
                                              4 Green complexion
                                              5 Blue complexion
                                              6 Sepia
                                              0 Preset
Turn white balance on/off awb 0 Off
                                                            1 On
                                                           1 Preset
Use special functions for
Use white balance.
On/Off awb_gain 0 Off
                                    1 On
                                    1 Preset
White balance
Functions wb_mode 0 Auto
                                        1 Sunny
                                        2 Cloudy
                                        3 Office
                                        4 Home
                                        0 Preset
AEC SENSOR aec 0 Off
                                 1 On
                                 1 Preset
AEC DSP aec2 0 Off
                        1 On
                        1 Preset
AE Level? ae_level -2 to 2 0
Exposure?
(not visible for me) aec_value 0 - 1200 204
Switches between the
following functions
agc_gain and gainceilling agc 0 Gain
1 Gain-Ceilling
1 Preset
agc_gain-group? agc_gain 0 single
30 31 fold
5
gainceiling-group? gainceiling 0 two fold To
6 128 fold
0
BPC? bpc 0 Off
1 On
0 Preset
WPC ? wpc 0 Off
1 On
1 Preset
Raw GMA ? raw_gma 0 Off
1 On
1 Preset
Lens Correction? lenc 0 Off
1 On
1 Preset
Horizontal reflection
(If the cam is on the side
side = vertical) hmirror 0 Off
1 On
1 Preset
Vertical mirroring
(When the cam is on the side
side = horizontal) vflip 0 Off
1 On
1 Preset
DCW (Downsize EN) ?
Downsizes the image dcw 0 Off
1 On
1 Preset
Displays color bars on
on the screen colorbar 0 Off
1 On
0 Preset
Enable face search face_detect 0 Off
1 On
0 Preset
Enable face recognition face_recognize 0 Off
1 On
0 Preset 

 Is there a variable for the LED?

**Comment by Haititei** [comment]
I´ve found the parameter: 
streamlight
1=on
2=off

**Comment by xenpac** [comment]
yes streamlight or flashlight, depending what use you want ;) 1=on 0=off
If you have a serial terminal connected to the camera, it will display the received commands received!!
